[package]
name = "zbrain-core"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Core engine, types and operation contracts for zbrain."

[lints]
workspace = true

[dependencies]

[dev-dependencies]
