//! Provider registry — the 17 recipes, ported verbatim as `static` data from
//! `src/core/ai/recipes/*.ts`.
//!
//! Pure data only. Behavioral hooks present in some TS recipes
//! (azure `resolveAuth`/`resolveOpenAICompatConfig`, openrouter
//! `resolveDefaultHeaders`, llama-server `probe`) are NOT ported here — they
//! belong to the provider trait layer (Phase 8 slice 3). Their pure-data
//! fields ARE ported.
//!
//! This file also **absorbs** the former standalone `embedding_pricing.rs`
//! table: pricing/dims live inside each recipe's embedding touchpoint, and
//! `lookup_pricing` (see `mod.rs`) derives from this single source of truth.

use super::types::{
    AuthEnv, ChatTouchpoint, EmbeddingTouchpoint, ExpansionTouchpoint, Implementation, Recipe,
    RerankerTouchpoint, Tier, Touchpoints,
};

/// The full provider registry. Order is stable but not semantically meaningful;
/// lookups are by id.
pub static REGISTRY: &[Recipe] = &[
    // ---- native: OpenAI ----
    Recipe {
        id: "openai",
        name: "OpenAI",
        tier: Tier::Native,
        implementation: Implementation::NativeOpenai,
        base_url_default: None,
        auth_env: Some(AuthEnv {
            required: &["OPENAI_API_KEY"],
            optional: &["OPENAI_ORG_ID", "OPENAI_PROJECT"],
            setup_url: Some("https://platform.openai.com/api-keys"),
        }),
        touchpoints: Touchpoints {
            embedding: Some(EmbeddingTouchpoint {
                models: &["text-embedding-3-large", "text-embedding-3-small"],
                default_dims: 1536,
                dims_options: Some(&[256, 512, 768, 1024, 1536, 3072]),
                cost_per_1m_tokens_usd: Some(0.13),
                price_last_verified: Some("2026-04-20"),
                max_batch_tokens: Some(100_000),
                chars_per_token: None,
                safety_factor: None,
                supports_multimodal: None,
                multimodal_models: None,
                user_provided_models: None,
                no_batch_cap: None,
            }),
            expansion: Some(ExpansionTouchpoint {
                models: &["gpt-5.2", "gpt-4o-mini"],
                cost_per_1m_tokens_usd: Some(0.15),
                price_last_verified: Some("2026-04-20"),
            }),
            chat: Some(ChatTouchpoint {
                models: &["gpt-5.2", "gpt-4o-mini"],
                supports_tools: true,
                supports_subagent_loop: true,
                supports_prompt_cache: Some(false),
                max_context_tokens: Some(200_000),
                cost_per_1m_input_usd: Some(1.25),
                cost_per_1m_output_usd: Some(10.0),
                price_last_verified: Some("2026-04-20"),
            }),
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Get an API key at https://platform.openai.com/api-keys, then `export OPENAI_API_KEY=...`",
        ),
    },
    // ---- native: Google Gemini ----
    Recipe {
        id: "google",
        name: "Google Gemini",
        tier: Tier::Native,
        implementation: Implementation::NativeGoogle,
        base_url_default: None,
        auth_env: Some(AuthEnv {
            required: &["GOOGLE_GENERATIVE_AI_API_KEY"],
            optional: &[],
            setup_url: Some("https://aistudio.google.com/apikey"),
        }),
        touchpoints: Touchpoints {
            embedding: Some(EmbeddingTouchpoint {
                models: &["gemini-embedding-001"],
                default_dims: 768,
                dims_options: Some(&[768, 1536, 3072]),
                cost_per_1m_tokens_usd: Some(0.15),
                price_last_verified: Some("2026-04-20"),
                max_batch_tokens: None,
                chars_per_token: None,
                safety_factor: None,
                supports_multimodal: None,
                multimodal_models: None,
                user_provided_models: None,
                no_batch_cap: None,
            }),
            expansion: Some(ExpansionTouchpoint {
                models: &["gemini-2.0-flash", "gemini-2.0-flash-lite"],
                cost_per_1m_tokens_usd: Some(0.10),
                price_last_verified: Some("2026-04-20"),
            }),
            chat: Some(ChatTouchpoint {
                models: &["gemini-2.0-flash-exp", "gemini-2.0-flash", "gemini-1.5-pro"],
                supports_tools: true,
                supports_subagent_loop: true,
                supports_prompt_cache: Some(false),
                max_context_tokens: Some(1_000_000),
                cost_per_1m_input_usd: Some(0.30),
                cost_per_1m_output_usd: Some(1.20),
                price_last_verified: Some("2026-04-20"),
            }),
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Get an API key at https://aistudio.google.com/apikey, then `export GOOGLE_GENERATIVE_AI_API_KEY=...`",
        ),
    },
    // ---- native: Anthropic ----
    Recipe {
        id: "anthropic",
        name: "Anthropic",
        tier: Tier::Native,
        implementation: Implementation::NativeAnthropic,
        base_url_default: None,
        auth_env: Some(AuthEnv {
            required: &["ANTHROPIC_API_KEY"],
            optional: &[],
            setup_url: Some("https://console.anthropic.com/settings/keys"),
        }),
        touchpoints: Touchpoints {
            embedding: None,
            expansion: Some(ExpansionTouchpoint {
                models: &["claude-haiku-4-5-20251001", "claude-sonnet-4-6"],
                cost_per_1m_tokens_usd: Some(0.25),
                price_last_verified: Some("2026-05-10"),
            }),
            chat: Some(ChatTouchpoint {
                models: &["claude-opus-4-7", "claude-sonnet-4-6", "claude-haiku-4-5-20251001"],
                supports_tools: true,
                supports_subagent_loop: true,
                supports_prompt_cache: Some(true),
                max_context_tokens: Some(200_000),
                cost_per_1m_input_usd: Some(3.0),
                cost_per_1m_output_usd: Some(15.0),
                price_last_verified: Some("2026-05-10"),
            }),
            reranker: None,
        },
        aliases: Some(&[
            ("claude-haiku-4-5", "claude-haiku-4-5-20251001"),
            ("claude-sonnet-4-6-20250929", "claude-sonnet-4-6"),
        ]),
        setup_hint: Some(
            "Get an API key at https://console.anthropic.com/settings/keys, then `export ANTHROPIC_API_KEY=...`",
        ),
    },
    // ---- openai-compat: Azure OpenAI ----
    Recipe {
        id: "azure-openai",
        name: "Azure OpenAI",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: None,
        auth_env: Some(AuthEnv {
            required: &[
                "AZURE_OPENAI_API_KEY",
                "AZURE_OPENAI_ENDPOINT",
                "AZURE_OPENAI_DEPLOYMENT",
            ],
            optional: &["AZURE_OPENAI_API_VERSION"],
            setup_url: Some(
                "https://learn.microsoft.com/en-us/azure/ai-services/openai/quickstart",
            ),
        }),
        touchpoints: Touchpoints {
            embedding: Some(EmbeddingTouchpoint {
                models: &[
                    "text-embedding-3-large",
                    "text-embedding-3-small",
                    "text-embedding-ada-002",
                ],
                default_dims: 1536,
                dims_options: Some(&[256, 512, 768, 1024, 1536, 3072]),
                cost_per_1m_tokens_usd: Some(0.13),
                price_last_verified: Some("2026-05-10"),
                max_batch_tokens: Some(8192),
                chars_per_token: None,
                safety_factor: None,
                supports_multimodal: None,
                multimodal_models: None,
                user_provided_models: None,
                no_batch_cap: None,
            }),
            expansion: None,
            chat: None,
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Azure portal \u{2192} Azure OpenAI resource. Set AZURE_OPENAI_API_KEY, AZURE_OPENAI_ENDPOINT, AZURE_OPENAI_DEPLOYMENT. Optionally AZURE_OPENAI_API_VERSION (default 2024-10-21).",
        ),
    },
    // ---- openai-compat: Alibaba DashScope ----
    Recipe {
        id: "dashscope",
        name: "Alibaba DashScope (\u{7075}\u{79ef})",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("https://dashscope-intl.aliyuncs.com/compatible-mode/v1"),
        auth_env: Some(AuthEnv {
            required: &["DASHSCOPE_API_KEY"],
            optional: &[],
            setup_url: Some("https://help.aliyun.com/zh/model-studio/getting-started/"),
        }),
        touchpoints: Touchpoints {
            embedding: Some(EmbeddingTouchpoint {
                models: &["text-embedding-v3", "text-embedding-v2"],
                default_dims: 1024,
                dims_options: Some(&[64, 128, 256, 512, 768, 1024]),
                cost_per_1m_tokens_usd: None,
                price_last_verified: None,
                max_batch_tokens: Some(8192),
                chars_per_token: Some(2.0),
                safety_factor: None,
                supports_multimodal: None,
                multimodal_models: None,
                user_provided_models: None,
                no_batch_cap: None,
            }),
            expansion: None,
            chat: None,
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Get an API key at https://help.aliyun.com/zh/model-studio/getting-started/, then `export DASHSCOPE_API_KEY=...`",
        ),
    },
    // ---- openai-compat: DeepSeek ----
    Recipe {
        id: "deepseek",
        name: "DeepSeek",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("https://api.deepseek.com/v1"),
        auth_env: Some(AuthEnv {
            required: &["DEEPSEEK_API_KEY"],
            optional: &[],
            setup_url: Some("https://platform.deepseek.com/api_keys"),
        }),
        touchpoints: Touchpoints {
            embedding: None,
            expansion: None,
            chat: Some(ChatTouchpoint {
                models: &["deepseek-chat", "deepseek-reasoner"],
                supports_tools: true,
                supports_subagent_loop: true,
                supports_prompt_cache: Some(false),
                max_context_tokens: Some(128_000),
                cost_per_1m_input_usd: Some(0.14),
                cost_per_1m_output_usd: Some(0.28),
                price_last_verified: Some("2026-04-20"),
            }),
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Get an API key at https://platform.deepseek.com/api_keys, then `export DEEPSEEK_API_KEY=...`",
        ),
    },
    // ---- openai-compat: Groq ----
    Recipe {
        id: "groq",
        name: "Groq",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("https://api.groq.com/openai/v1"),
        auth_env: Some(AuthEnv {
            required: &["GROQ_API_KEY"],
            optional: &[],
            setup_url: Some("https://console.groq.com/keys"),
        }),
        touchpoints: Touchpoints {
            embedding: None,
            expansion: None,
            chat: Some(ChatTouchpoint {
                models: &[
                    "llama-3.3-70b-versatile",
                    "llama-3.1-8b-instant",
                    "gpt-oss-20b",
                    "gpt-oss-120b",
                ],
                supports_tools: true,
                supports_subagent_loop: true,
                supports_prompt_cache: Some(false),
                max_context_tokens: Some(131_072),
                cost_per_1m_input_usd: Some(0.59),
                cost_per_1m_output_usd: Some(0.79),
                price_last_verified: Some("2026-04-20"),
            }),
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Get an API key at https://console.groq.com/keys, then `export GROQ_API_KEY=...`",
        ),
    },
    // ---- openai-compat: llama.cpp llama-server (reranker, local) ----
    Recipe {
        id: "llama-server-reranker",
        name: "llama.cpp llama-server (reranker, local)",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("http://localhost:8081/v1"),
        auth_env: Some(AuthEnv {
            required: &[],
            optional: &["LLAMA_SERVER_RERANKER_BASE_URL", "LLAMA_SERVER_RERANKER_API_KEY"],
            setup_url: Some(
                "https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md",
            ),
        }),
        touchpoints: Touchpoints {
            embedding: None,
            expansion: None,
            chat: None,
            reranker: Some(RerankerTouchpoint {
                models: &[],
                default_model: "qwen3-reranker-4b",
                cost_per_1m_tokens_usd: Some(0.0),
                price_last_verified: Some("2026-05-23"),
                max_payload_bytes: 5_000_000,
                path: Some("/rerank"),
                default_timeout_ms: Some(30_000),
            }),
        },
        aliases: None,
        setup_hint: Some(
            "Build llama.cpp, then `llama-server --model <gguf-path> --alias <short-id> --reranking --port 8081`. The --alias makes provider:model strings short (without it, /v1/models defaults the id to the gguf file path). Then `zbrain config set search.reranker.model llama-server-reranker:<short-id>` and `zbrain config set provider_base_urls.llama-server-reranker http://<host>:8081/v1`.",
        ),
    },
    // ---- openai-compat: llama.cpp llama-server (local) ----
    Recipe {
        id: "llama-server",
        name: "llama.cpp llama-server (local)",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("http://localhost:8080/v1"),
        auth_env: Some(AuthEnv {
            required: &[],
            optional: &["LLAMA_SERVER_BASE_URL", "LLAMA_SERVER_API_KEY"],
            setup_url: Some(
                "https://github.com/ggml-org/llama.cpp/blob/master/tools/server/README.md",
            ),
        }),
        touchpoints: Touchpoints {
            embedding: Some(EmbeddingTouchpoint {
                models: &[],
                default_dims: 0,
                dims_options: None,
                cost_per_1m_tokens_usd: Some(0.0),
                price_last_verified: Some("2026-05-10"),
                max_batch_tokens: None,
                chars_per_token: None,
                safety_factor: None,
                supports_multimodal: None,
                multimodal_models: None,
                user_provided_models: Some(true),
                no_batch_cap: Some(true),
            }),
            expansion: None,
            chat: None,
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Build llama.cpp, then `llama-server --model <gguf-path> --embeddings`. Set --embedding-model llama-server:<id> + --embedding-dimensions <N>.",
        ),
    },
    // ---- openai-compat: MiniMax ----
    Recipe {
        id: "minimax",
        name: "MiniMax (\u{6d77}\u{87ba}AI)",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("https://api.minimaxi.com/v1"),
        auth_env: Some(AuthEnv {
            required: &["MINIMAX_API_KEY"],
            optional: &["MINIMAX_GROUP_ID"],
            setup_url: Some("https://www.minimaxi.com/document/guides/embeddings"),
        }),
        touchpoints: Touchpoints {
            embedding: Some(EmbeddingTouchpoint {
                models: &["embo-01"],
                default_dims: 1536,
                dims_options: None,
                cost_per_1m_tokens_usd: Some(0.07),
                price_last_verified: Some("2026-05-09"),
                max_batch_tokens: Some(4096),
                chars_per_token: None,
                safety_factor: None,
                supports_multimodal: None,
                multimodal_models: None,
                user_provided_models: None,
                no_batch_cap: None,
            }),
            expansion: None,
            chat: None,
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Get an API key at https://www.minimaxi.com, then `export MINIMAX_API_KEY=...`",
        ),
    },
    // ---- openai-compat: Ollama (local) ----
    Recipe {
        id: "ollama",
        name: "Ollama (local)",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("http://localhost:11434/v1"),
        auth_env: Some(AuthEnv {
            required: &[],
            optional: &["OLLAMA_BASE_URL", "OLLAMA_API_KEY"],
            setup_url: Some("https://ollama.ai"),
        }),
        touchpoints: Touchpoints {
            embedding: Some(EmbeddingTouchpoint {
                models: &["nomic-embed-text", "mxbai-embed-large", "all-minilm"],
                default_dims: 768,
                dims_options: None,
                cost_per_1m_tokens_usd: Some(0.0),
                price_last_verified: Some("2026-04-20"),
                max_batch_tokens: None,
                chars_per_token: None,
                safety_factor: None,
                supports_multimodal: None,
                multimodal_models: None,
                user_provided_models: None,
                no_batch_cap: Some(true),
            }),
            expansion: None,
            chat: None,
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Install Ollama from https://ollama.ai, then `ollama pull nomic-embed-text` and `ollama serve`.",
        ),
    },
    // ---- openai-compat: OpenRouter ----
    Recipe {
        id: "openrouter",
        name: "OpenRouter",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("https://openrouter.ai/api/v1"),
        auth_env: Some(AuthEnv {
            required: &["OPENROUTER_API_KEY"],
            optional: &["OPENROUTER_BASE_URL", "OPENROUTER_REFERER", "OPENROUTER_TITLE"],
            setup_url: Some("https://openrouter.ai/settings/keys"),
        }),
        touchpoints: Touchpoints {
            embedding: Some(EmbeddingTouchpoint {
                models: &["openai/text-embedding-3-small"],
                default_dims: 1536,
                dims_options: Some(&[512, 768, 1024, 1536]),
                cost_per_1m_tokens_usd: Some(0.02),
                price_last_verified: Some("2026-05-20"),
                max_batch_tokens: Some(300_000),
                chars_per_token: None,
                safety_factor: None,
                supports_multimodal: None,
                multimodal_models: None,
                user_provided_models: None,
                no_batch_cap: None,
            }),
            expansion: None,
            chat: Some(ChatTouchpoint {
                models: &[
                    "openai/gpt-5.2",
                    "openai/gpt-5.2-chat",
                    "openai/gpt-5.5",
                    "anthropic/claude-haiku-4.5",
                    "anthropic/claude-sonnet-4.6",
                    "anthropic/claude-opus-4.7",
                    "google/gemini-3-flash-preview",
                    "deepseek/deepseek-chat",
                ],
                supports_tools: true,
                supports_subagent_loop: false,
                supports_prompt_cache: Some(false),
                max_context_tokens: None,
                cost_per_1m_input_usd: None,
                cost_per_1m_output_usd: None,
                price_last_verified: Some("2026-05-20"),
            }),
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Get an API key at https://openrouter.ai/settings/keys, then `export OPENROUTER_API_KEY=...` and use `openrouter:<provider>/<model>`. Optional overrides: OPENROUTER_BASE_URL (proxy), OPENROUTER_REFERER (attribution URL), OPENROUTER_TITLE (attribution name).",
        ),
    },
    // ---- openai-compat: Together AI ----
    Recipe {
        id: "together",
        name: "Together AI",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("https://api.together.xyz/v1"),
        auth_env: Some(AuthEnv {
            required: &["TOGETHER_API_KEY"],
            optional: &[],
            setup_url: Some("https://api.together.ai/settings/api-keys"),
        }),
        touchpoints: Touchpoints {
            embedding: None,
            expansion: None,
            chat: Some(ChatTouchpoint {
                models: &[
                    "Qwen/Qwen2.5-72B-Instruct-Turbo",
                    "meta-llama/Llama-3.3-70B-Instruct-Turbo",
                    "deepseek-ai/DeepSeek-V3",
                    "mistralai/Mixtral-8x22B-Instruct-v0.1",
                ],
                supports_tools: true,
                supports_subagent_loop: true,
                supports_prompt_cache: Some(false),
                max_context_tokens: Some(131_072),
                cost_per_1m_input_usd: Some(0.88),
                cost_per_1m_output_usd: Some(0.88),
                price_last_verified: Some("2026-04-20"),
            }),
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Get an API key at https://api.together.ai/settings/api-keys, then `export TOGETHER_API_KEY=...`",
        ),
    },
    // ---- openai-compat: Voyage AI ----
    Recipe {
        id: "voyage",
        name: "Voyage AI",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("https://api.voyageai.com/v1"),
        auth_env: Some(AuthEnv {
            required: &["VOYAGE_API_KEY"],
            optional: &[],
            setup_url: Some("https://dash.voyageai.com/api-keys"),
        }),
        touchpoints: Touchpoints {
            embedding: Some(EmbeddingTouchpoint {
                models: &[
                    "voyage-4-large",
                    "voyage-4",
                    "voyage-4-lite",
                    "voyage-4-nano",
                    "voyage-3.5",
                    "voyage-3-large",
                    "voyage-3",
                    "voyage-3-lite",
                    "voyage-code-3",
                    "voyage-finance-2",
                    "voyage-law-2",
                    "voyage-multimodal-3",
                ],
                default_dims: 1024,
                dims_options: None,
                cost_per_1m_tokens_usd: Some(0.18),
                price_last_verified: Some("2026-04-20"),
                max_batch_tokens: Some(120_000),
                chars_per_token: Some(1.0),
                safety_factor: Some(0.5),
                supports_multimodal: Some(true),
                multimodal_models: Some(&["voyage-multimodal-3"]),
                user_provided_models: None,
                no_batch_cap: None,
            }),
            expansion: None,
            chat: None,
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Get an API key at https://dash.voyageai.com/api-keys, then `export VOYAGE_API_KEY=...`",
        ),
    },
    // ---- openai-compat: ZeroEntropy ----
    Recipe {
        id: "zeroentropyai",
        name: "ZeroEntropy",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("https://api.zeroentropy.dev/v1"),
        auth_env: Some(AuthEnv {
            required: &["ZEROENTROPY_API_KEY"],
            optional: &[],
            setup_url: Some("https://dashboard.zeroentropy.dev"),
        }),
        touchpoints: Touchpoints {
            embedding: Some(EmbeddingTouchpoint {
                models: &["zembed-1"],
                default_dims: 2560,
                dims_options: None,
                cost_per_1m_tokens_usd: Some(0.05),
                price_last_verified: Some("2026-05-14"),
                max_batch_tokens: Some(120_000),
                chars_per_token: Some(1.0),
                safety_factor: Some(0.5),
                supports_multimodal: Some(false),
                multimodal_models: None,
                user_provided_models: None,
                no_batch_cap: None,
            }),
            expansion: None,
            chat: None,
            reranker: Some(RerankerTouchpoint {
                models: &["zerank-2", "zerank-1", "zerank-1-small"],
                default_model: "zerank-2",
                cost_per_1m_tokens_usd: Some(0.025),
                price_last_verified: Some("2026-05-14"),
                max_payload_bytes: 5_000_000,
                path: None,
                default_timeout_ms: None,
            }),
        },
        aliases: None,
        setup_hint: Some(
            "Get an API key at https://dashboard.zeroentropy.dev, then `export ZEROENTROPY_API_KEY=...`",
        ),
    },
    // ---- openai-compat: Zhipu AI ----
    Recipe {
        id: "zhipu",
        name: "Zhipu AI (\u{667a}\u{8c31}AI BigModel)",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("https://open.bigmodel.cn/api/paas/v4"),
        auth_env: Some(AuthEnv {
            required: &["ZHIPUAI_API_KEY"],
            optional: &[],
            setup_url: Some("https://open.bigmodel.cn/"),
        }),
        touchpoints: Touchpoints {
            embedding: Some(EmbeddingTouchpoint {
                models: &["embedding-3", "embedding-2"],
                default_dims: 1024,
                dims_options: Some(&[256, 512, 1024, 2048]),
                cost_per_1m_tokens_usd: None,
                price_last_verified: None,
                max_batch_tokens: Some(8192),
                chars_per_token: Some(2.0),
                safety_factor: None,
                supports_multimodal: None,
                multimodal_models: None,
                user_provided_models: None,
                no_batch_cap: None,
            }),
            expansion: None,
            chat: None,
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Get an API key at https://open.bigmodel.cn/, then `export ZHIPUAI_API_KEY=...`",
        ),
    },
    // ---- openai-compat: LiteLLM Proxy (universal) ----
    Recipe {
        id: "litellm",
        name: "LiteLLM Proxy (universal)",
        tier: Tier::OpenaiCompat,
        implementation: Implementation::OpenaiCompatible,
        base_url_default: Some("http://localhost:4000"),
        auth_env: Some(AuthEnv {
            required: &[],
            optional: &["LITELLM_BASE_URL", "LITELLM_API_KEY"],
            setup_url: Some("https://docs.litellm.ai/docs/proxy/quick_start"),
        }),
        touchpoints: Touchpoints {
            embedding: Some(EmbeddingTouchpoint {
                models: &[],
                default_dims: 0,
                dims_options: None,
                cost_per_1m_tokens_usd: None,
                price_last_verified: Some("2026-04-20"),
                max_batch_tokens: None,
                chars_per_token: None,
                safety_factor: None,
                supports_multimodal: Some(true),
                multimodal_models: None,
                user_provided_models: Some(true),
                no_batch_cap: Some(true),
            }),
            expansion: None,
            chat: None,
            reranker: None,
        },
        aliases: None,
        setup_hint: Some(
            "Run LiteLLM (https://docs.litellm.ai) in front of any provider; set LITELLM_BASE_URL + pass --embedding-model litellm:<model> and --embedding-dimensions <N>.",
        ),
    },
];
